name: env
channels:
- anaconda 
- defaults
dependencies:
- pytorch
- torchvision
- python=3.8.10
- scipy==1.6.2
- pip
- pip:
  - matplotlib==3.4.1
  - opencv-python==4.5.1.48
  - spacy==3.0.5
  - numpy==1.22.4
  - inflect
  - nltk
  - timm